FROM python:3.11-slim

WORKDIR /app

# Копируем только проект Adalya
COPY expo_pos_adalya/ .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
